// Removes empty strings, in our case remove arr strings generated by formData obj
function filterEmptyArr(arr) {
  return (typeof arr == 'string' ? JSON.parse(arr) : arr).filter((el) => el !== "");
}

// Get image file
function getImagePath(req, forDeleteUrl = undefined) {
  if(!req.file){
    return false;  
  }
  if (forDeleteUrl) {
    const fileName = forDeleteUrl.split("/photo-shoot/")[1];
    const imgFile = `${process.env.BACKEND_IMAGE_FOLDER || ""}${fileName}`;
    return imgFile;
  }
  const siteUrl = req.protocol + "://" + req.get("host");
  const fileDestination = req.file.destination.replace(
    process.env.BACKEND_IMAGE_FOLDER,
    ""
  );
  const imgFile = `${siteUrl}/photo-shoot/${fileDestination}/${req.file.filename}`;

  return imgFile;
  // Before and after replacement
  // --------------------------
  // http://localhost:3000/photo-shoot/backend/images/2021/07/test-1626796315740.jpg
  // http://localhost:3000/photo-shoot/images/2021/07/test-1626796315740.jpg
}

module.exports = {
  filterEmptyArr,
  getImagePath,
};
