// Removes empty strings, in our case remove arr strings generated by formData obj
const filterEmptyArr = (arr) => arr.filter((el) => el !== "");



async function createPhoto(req, res, next) {
  getImagePath(req);
  res.status(200).json({ message: "List Users" });
}
module.exports = {
  createPhoto,
};

function getImagePath(req, forDeleteUrl = undefined) {

  if(forDeleteUrl){
    const fileName = forDeleteUrl.split("/")[forDeleteUrl.split("/").length - 1];
    const path = `${process.env.BACKEND_IMAGE_FOLDER || ""}images/${fileName}`;
    return path;
  }
  const siteUrl = req.protocol + "://" + req.get("host");
  const fileDestination = req.file.destination.replace(process.env.BACKEND_IMAGE_FOLDER, "");
  const imgFile = `${siteUrl}/photo-shoot/${fileDestination}/${req.file.filename}`

  return imgFile;
  // Before and after replacement
  // --------------------------
  // http://localhost:3000/photo-shoot/backend/images/2021/07/test-1626796315740.jpg
  // http://localhost:3000/photo-shoot/images/2021/07/test-1626796315740.jpg
}
